# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCRecordingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CCRecordingDemo
  pod 'BaiduMobStat', '~> 4.4.0'
  pod 'CCRecording'
  
end
